# Generated by Django 3.0 on 2023-04-28 19:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_count', models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('price', models.FloatField()),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='media/id_photos')),
                ('privacy_policy', models.BooleanField()),
                ('delivery_way', models.CharField(choices=[('', '--- Choose Delivery Way ---'), ('delivery', 'Delivery'), ('receive', 'Receive')], max_length=255)),
                ('city', models.CharField(choices=[('', '--- Choose city ---'), ('amman', 'Amman'), ('irbid', 'Irbid'), ('zarqa', 'Al-Zarqa'), ('aqapa', 'Al-Aqapa'), ('maan', 'Maan'), ('mafraq', 'Al-Mafraq'), ('karak', 'Al-Karak'), ('tafilah', 'Al-Tafilah'), ('madaba', 'Madaba'), ('jarash', 'Jarash')], max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('eq_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_name', to='equipment.Equipment', verbose_name='equipment')),
            ],
        ),
    ]
