# Generated by Django 3.0 on 2023-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('available', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/eq_pic')),
                ('description', models.TextField()),
                ('privacy_policy', models.BooleanField()),
                ('price', models.FloatField()),
            ],
        ),
    ]
