# Generated by Django 3.0 on 2023-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('major', models.CharField(choices=[('', '--- Choose Major ---'), ('Pediatric', 'Pediatric nursing'), ('Elderly', 'Elderly nursing'), ('Kidney', 'Kidney disease'), ('Other', 'Other')], max_length=255, null=True)),
                ('session_time', models.CharField(choices=[('', '--- Choose Session time ---'), ('8-9', '08:00 AM - 09:00 AM'), ('9-10', '09:00 AM - 10:00 AM'), ('10-11', '10:00 AM - 11:00 AM'), ('11-12', '11:00 AM - 12:00 PM'), ('12-1', '12:00 PM - 01:00 PM'), ('1-2', '01:00 PM - 02:00 PM'), ('2-3', '02:00 PM - 03:00 PM'), ('3-4', '03:00 PM - 04:00 PM'), ('4-5', '04:00 PM - 05:00 PM'), ('5-6', '05:00 PM - 06:00 PM')], max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('APPROVED', 'Approved'), ('UNAVAILABLE', 'Unavailable'), ('DONE', 'Done')], default='AVAILABLE', max_length=255, null=True)),
                ('type', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('NORMAL', 'Normal')], default='NORMAL', max_length=255, null=True)),
            ],
        ),
    ]
