# Generated by Django 3.0 on 2023-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20230428_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='city',
            field=models.CharField(blank=True, choices=[('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'AQABA')], max_length=255, null=True),
        ),
    ]
