# Generated by Django 3.0 on 2023-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_auto_20230430_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='city',
            field=models.CharField(choices=[('', '--- Choose a City ---'), ('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'IRBID')], max_length=255, null=True),
        ),
    ]
