# Generated by Django 3.0 on 2023-04-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='state',
        ),
    ]
