# Generated by Django 3.0 on 2023-04-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_staff_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurserequest',
            name='city',
            field=models.CharField(blank=True, choices=[('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'AQABA')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='city',
            field=models.CharField(blank=True, choices=[('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'AQABA')], max_length=255, null=True),
        ),
    ]
