# Generated by Django 3.0 on 2023-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230430_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurserequest',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='certificate',
            field=models.ImageField(null=True, upload_to='media/certifications'),
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='city',
            field=models.CharField(choices=[('', '--- Choose a City ---'), ('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'AQABA')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='major',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/doctor_photo'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(choices=[('', '--- Choose a City ---'), ('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'AQABA')], max_length=255, null=True),
        ),
    ]
