# Generated by Django 3.0 on 2023-04-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20230430_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurserequest',
            name='exp_year',
            field=models.IntegerField(null=True),
        ),
    ]
