# Generated by Django 3.0 on 2023-05-08 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20230430_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='rate',
        ),
        migrations.AlterField(
            model_name='nurserequest',
            name='city',
            field=models.CharField(choices=[('', '--- Choose a City ---'), ('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'IRBID')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='city',
            field=models.CharField(choices=[('', '--- Choose a City ---'), ('AMMAN', 'AMMAN'), ('ZARQA', 'ZARQA'), ('KARAK', 'KARAK'), ('MAFRAQ', 'MAFRAQ'), ('AQABA', 'AQABA'), ('IRBID', 'IRBID')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.PositiveIntegerField(blank=True, default=5, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff', verbose_name='Doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
